### ISSUE TITLE
Profitbricks rate limit cause the .tfstate to lose track of resources

### ISSUE THREAD

**Issue by einyx** [terraform-providers/terraform-provider-profitbricks#16]
### Terraform Version
Terraform v0.10.8

### Affected Resource(s)

- profitbricks_ipblock
- profitbricks_datacanter
- profitbricks_iplan
- profitbricks_server

### Terraform Configuration Files
```hcl
//Virtual Data Center
resource "profitbricks_datacenter" "xx" {
  name = "xx.xx.xx"
  location = "xx/xx"
  description = "xx Datacenter"
}
//Public lan
resource "profitbricks_lan" "xxx" {
  datacenter_id = "${profitbricks_datacenter.xxx.id}"
  public = true
  name = "xxx.xxx.xxx"
}

//Private lan
resource "profitbricks_lan" "xxx-private" {
  datacenter_id = "${profitbricks_datacenter.xxx.id}"
  public = false
  name = "xx-private.xx.xx.xx"
}

//IP Block
resource "profitbricks_ipblock" "xxx" {
  location = "${profitbricks_datacenter.xx.location}"
  size = 4
}

//Public lan
resource "profitbricks_lan" "xxx" {
  datacenter_id = "${profitbricks_datacenter.xxxx.id}"
  public = true
  name = "xxx.xxx.xx"
}

//IP Block
resource "profitbricks_ipblock" "xxxx" {
  location = "${profitbricks_datacenter.xxx.location}"
  size = 4
}

resource "profitbricks_server" "xxxx" {
  name              = "shared-xxx"
  datacenter_id     = "${profitbricks_datacenter.xxx.id}"
  cores             = 2
  ram               = 1024
  availability_zone = "ZONE_1"
  cpu_family        = "AMD_OPTERON"

  volume {
    name           = "shared-xx"
    image_name     = "xxx-xxx-xxx-xxx-xxxxx"
    size           = 20
    disk_type      = "SSD"
  }

  nic {
    lan = "${profitbricks_lan.shared-private.id}"
    dhcp = true
    firewall_active = true
    firewall {
      protocol = "TCP"
      name = "SSH"
      port_range_start = 22
      port_range_end = 22
    }
  }
}

```

### Debug Output
```
2017/11/02 10:27:48 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* profitbricks_server.ldap: Error fetching image/snapshot: Rate Limit Exceeded
2017/11/02 10:27:48 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_server.ldap: Error fetching image/snapshot: Rate Limit Exceeded
2017/11/02 10:27:48 [TRACE] [walkApply] Exiting eval tree: profitbricks_server.ldap
2017/11/02 10:27:48 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* profitbricks_server.gitlab: Error fetching image/snapshot: Rate Limit Exceeded
2017/11/02 10:27:48 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
```

### Panic Output
```
* profitbricks_lan.shared-private: unexpected EOF
2017/10/30 14:04:42 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* profitbricks_lan.shared-private: unexpected EOF
2017/10/30 14:04:42 [TRACE] [walkApply] Exiting eval tree: profitbricks_lan.shared-private
2017/10/30 14:04:42 [TRACE] dag/walk: upstream errored, not walking "profitbricks_server.postgres"
2017/10/30 14:04:42 [TRACE] dag/walk: upstream errored, not walking "profitbricks_server.ldap"
2017/10/30 14:04:42 [TRACE] dag/walk: upstream errored, not walking "profitbricks_server.registry"
2017/10/30 14:04:42 [TRACE] dag/walk: upstream errored, not walking "profitbricks_server.gitlab"
2017/10/30 14:04:42 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/10/30 14:04:42 [TRACE] dag/walk: upstream errored, not walking "provider.profitbricks (close)"
2017/10/30 14:04:42 [TRACE] dag/walk: upstream errored, not walking "root"
2017/10/30 14:04:42 [TRACE] Preserving existing state lineage "75d48b74-3857-42c6-b87d-142f0d4e376e"
2017/10/30 14:04:42 [TRACE] Preserving existing state lineage "75d48b74-3857-42c6-b87d-142f0d4e376e"
2017/10/30 14:04:42 [TRACE] Preserving existing state lineage "75d48b74-3857-42c6-b87d-142f0d4e376e"
2017/10/30 14:04:42 [DEBUG] plugin: waiting for all plugin processes to complete...
2017-10-30T14:04:42.164Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
```

### Expected Behavior
The rate limit should tell TF to keep trying and exit gracefully if not be able to do so.

### Actual Behavior
After getting limited for a while TF crashes and the state actually get's corrupted.
A new apply will recreate again the same resources every time, causing servers duplicates.

### Steps to Reproduce
1. `terraform apply`

**Comment by jasmingacic** [comment]
@einyx The problem you are facing isn't actually a terraform problem. Since server is depending on other resources like, lan, dc, snapshot if one of those fails with the similar message Terraform isn't able to create the server. Since the server was not created it doesn't get recorded in `.tfstate` therefore it gets recreated when you invoke `terraform apply`. 

Also this kind of error qualifies as panic since Terraform is not able to interact with the Cloud API retrying wouldn't be possible either. 

I would suggest the following, make resources depending on each other using [depends_on ](https://www.terraform.io/intro/getting-started/dependencies.html). Judging from the output i would make `profitbricks_server` objects depend on each other. That way you would be saving your request rate limit. 

One possible option would be to ask ProfitBricks to bump up you request rate limit from 125 to 300.

**Comment by einyx** [comment]
Is an hard limit apparently

**Comment by edevenport** [comment]
Hello @einyx - I heard that you were still encountering issues with the Terraform provider, particularly in regards to rate limiting. I don't think the above Terraform config is what you are actually using for your tests? When I attempted to test the above example myself, it was missing required parameters. The example also builds a single server whereas I think you are attempting to build three?

I adjusted the config locally (adding a missing parameter and adjusting the resource names) and tested the config. A single server was successfully built.

I then added a count of 3, but hit the max retry limit. I increased the retry limit in my config to 200 and tried again. All three servers were built successfully. I never encountered the API rate limit.

If you can provide a more recent copy of your Terraform config, I am happy to test it locally and optimize it as necessary. There are a couple of things we can try.

1. Terraform uses a default `parallelism` of 10. Depending on your local config and the desired infrastructure, this can be reduced with the `--parallelism` CLI parameter which might help in your case. I would need to see and test the config to know if this is necessary.

2. As Jasmin suggested, using `depends_on` might help as well. I believe this affects `parallelism` and can reduce requests by waiting for dependent resources to be built first at a more reasonable rate. I have used the parameter myself with some success to workaround various limitations.

3. Depending on the size of the infrastructure being built, it might also be necessary to increase the [retries](https://www.terraform.io/docs/providers/profitbricks/index.html#retries) value.

I should know more once I review the config being used. Thank you.
