### ISSUE TITLE
dhcp=false ignored for nic.0

### ISSUE THREAD

**Issue by benschmi** [terraform-providers/terraform-provider-profitbricks#50]
### Terraform Version
$ terraform -v
Terraform v0.11.11

* provider.profitbricks v1.4.2

### Affected Resource(s)

- profitbricks_server

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "profitbricks_server" "test" {
  name              = "test-vm-1"
  datacenter_id     = "${profitbricks_datacenter.dc-01.id}"
  cores             = 1
  ram               = 1024
  availability_zone = "AUTO"
  cpu_family        = "AMD_OPTERON"
  image_name        = "centos:latest"
  ssh_key_path      = ["${var.ssh_public_keys}"]
  image_password    = "${var.console_password}"

  volume = [
    {
      name           = "test-vm-boot"
      size           = 10
      disk_type      = "HDD"
    },
  ]

  nic = [
    {
      lan  = "${profitbricks_lan.mgm_lan.id}"
      dhcp = false
      name = "publicNIC"
      firewall_active = true
      ip            = "192.168.10.100"
    },
  ]
}
```

### Expected Behavior
DHCP has been disabled for nic.0

### Actual Behavior
DHCP is enabled for nic.0

### Steps to Reproduce
$ terraform apply
profitbricks_datacenter.dc-01: Refreshing state... (ID: b6b8a6ec-f35a-462c-9dd3-73fc6958335e)
profitbricks_lan.public_lan: Refreshing state... (ID: 2)
profitbricks_lan.mgm_lan: Refreshing state... (ID: 4)
profitbricks_server.test: Refreshing state... (ID: ea58213a-18fa-419a-8ae4-f2c74b9f6718)
profitbricks_volume.vol: Refreshing state... (ID: 68b2e2c6-2f84-411c-bd0d-acdc00d25067)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + profitbricks_server.test
      id:                         <computed>
      availability_zone:          "AUTO"
      boot_cdrom:                 <computed>
      boot_image:                 <computed>
      boot_volume:                <computed>
      cores:                      "1"
      cpu_family:                 "AMD_OPTERON"
      datacenter_id:              "b6b8a6ec-f35a-462c-9dd3-73fc6958335e"
      firewallrule_id:            <computed>
      image_name:                 "centos:latest"
      image_password:             <sensitive>
      name:                       "test-vm-1"
      nic.#:                      "1"
      nic.0.dhcp:                 "false"
      nic.0.firewall_active:      "true"
      nic.0.ip:                   "192.168.10.100"
      nic.0.ips.#:                <computed>
      nic.0.lan:                  "0"
      nic.0.name:                 "publicNIC"
      primary_ip:                 <computed>
      primary_nic:                <computed>
      ram:                        "1024"
      ssh_key_path.#:             "1"
      ssh_key_path.0:             ".ssh/id_rsa.pub"
      volume.#:                   "1"
      volume.0.availability_zone: <computed>
      volume.0.bus:               <computed>
      volume.0.disk_type:         "HDD"
      volume.0.image_aliases.#:   <computed>
      volume.0.licence_type:      <computed>
      volume.0.name:              "test-vm-boot"
      volume.0.size:              "10"

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

profitbricks_server.test: Creating...
  availability_zone:          "" => "AUTO"
  boot_cdrom:                 "" => "<computed>"
  boot_image:                 "" => "<computed>"
  boot_volume:                "" => "<computed>"
  cores:                      "" => "1"
  cpu_family:                 "" => "AMD_OPTERON"
  datacenter_id:              "" => "b6b8a6ec-f35a-462c-9dd3-73fc6958335e"
  firewallrule_id:            "" => "<computed>"
  image_name:                 "" => "centos:latest"
  image_password:             "<sensitive>" => "<sensitive>"
  name:                       "" => "test-vm-1"
  nic.#:                      "" => "1"
  nic.0.dhcp:                 "" => "false"
  nic.0.firewall_active:      "" => "true"
  nic.0.ip:                   "" => "192.168.10.100"
  nic.0.ips.#:                "" => "<computed>"
  nic.0.lan:                  "" => "3"
  nic.0.name:                 "" => "publicNIC"
  primary_ip:                 "" => "<computed>"
  primary_nic:                "" => "<computed>"
  ram:                        "" => "1024"
  ssh_key_path.#:             "" => "1"
  ssh_key_path.0:             "" => ".ssh/id_rsa.pub"
  volume.#:                   "" => "1"
  volume.0.availability_zone: "" => "<computed>"
  volume.0.bus:               "" => "<computed>"
  volume.0.disk_type:         "" => "HDD"
  volume.0.image_aliases.#:   "" => "<computed>"
  volume.0.licence_type:      "" => "<computed>"
  volume.0.name:              "" => "test-vm-boot"
  volume.0.size:              "" => "10"
profitbricks_server.test: Still creating... (10s elapsed)
profitbricks_server.test: Still creating... (20s elapsed)
profitbricks_server.test: Still creating... (30s elapsed)
profitbricks_server.test: Still creating... (40s elapsed)
profitbricks_server.test: Still creating... (50s elapsed)
profitbricks_server.test: Still creating... (1m0s elapsed)
profitbricks_server.test: Still creating... (1m10s elapsed)
profitbricks_server.test: Still creating... (1m20s elapsed)
profitbricks_server.test: Still creating... (1m30s elapsed)
profitbricks_server.test: Still creating... (1m40s elapsed)
profitbricks_server.test: Still creating... (1m50s elapsed)
profitbricks_server.test: Creation complete after 1m56s (ID: fdd85150-e4a0-4357-80a5-cf1560e8b795)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

**Comment by Ntr0** [comment]
Closed with #51
