### ISSUE TITLE
support for terraform 0.12.x

### ISSUE THREAD

**Issue by lachnerd** [terraform-providers/terraform-provider-profitbricks#60]
Hi,
i wonder if there is still development going on here.

I'd like to use latest terraform features but this provider doesnt' support it.

Last release is over 9 months old.

So are there plans to upgrade this or is profitbricks provider still active or do i have to use ionos driver or something else ?

**Comment by pennycoders** [comment]
Hi @lachnerd,

A new release is out: v1.5.0. It also adds support for Terraform v0.12

https://releases.hashicorp.com/terraform-provider-profitbricks/1.5.0/
https://github.com/terraform-providers/terraform-provider-profitbricks/graphs/contributors

Regards,

Alex
