### ISSUE TITLE
 terraform-provider-profitbricks still alive ?

### ISSUE THREAD

**Issue by lachnerd** [terraform-providers/terraform-provider-profitbricks#61]
nothing new since June 26 2019 - is this still alive ?

**Comment by vadimcucereanu** [comment]
Hi @lachnerd.

The module is still alive. In the following weeks we plan to update it with the latest Ionos Go SDK version. 

Kind regards

**Comment by ravibhure** [comment]
Hi @vadimcucereanu, Is there any plans to add new feature to the current version ?
I would like to have `count` for `profitbricks_server` resources.

**Comment by benschmi** [comment]
Hi @ravibhure. The `count` parameter is already implemented and can be used immediatly.

**Comment by ravibhure** [comment]
Awesome! 
@benschmi, I am following the doc https://www.terraform.io/docs/providers/profitbricks/r/profitbricks_server.html, it is not showing up the argument reference.

**Comment by ravibhure** [comment]
Thank you @benschmi , I got it :+1:

**Comment by lachnerd** [comment]
Can you be a little more precise ?
Is there any release date planned?
Using the old terraform version is becoming more and more painful but as long as there is no 0.12 compatible profitbricks version we are unfortunately forced to.

**Comment by benschmi** [comment]
@lachnerd, working on it :) Please see https://github.com/terraform-providers/terraform-provider-profitbricks/pull/65

**Comment by pennycoders** [comment]
Hi @lachnerd 

A new version is out (1.5.0), with Terraform v0.12 support:

- https://releases.hashicorp.com/terraform-provider-profitbricks/1.5.0/
- https://github.com/terraform-providers/terraform-provider-profitbricks/releases

Please let us know if you need any help.

Regards,

Alex.
