### ISSUE TITLE
Increase node count is not executed

### ISSUE THREAD

**Issue by ando47** [terraform-providers/terraform-provider-profitbricks#78]
Hi, 
**Terraform Version**

Terraform v0.13.2
+ provider registry.terraform.io/terraform-providers/profitbricks v1.5.6

**Affected Resource(s)**
The issue turned up in the combination of the following resource:
profitbricks_k8s_node_pool

**Expected Behavior**
New Worker nodes to be created according to config

**Actual Behavior**
When increasing the node_count inside a nodepool, the change is not executed.

**Hint**
Autscaling is not enabled in the manifest.

Attached: the config.
[main1.zip](https://github.com/terraform-providers/terraform-provider-profitbricks/files/5237829/main1.zip)

**Comment by pennycoders** [comment]
T

**Comment by pennycoders** [comment]
Hi,

This issue should be fixed in the **v1.5.7** which was just released today. Can you please check?

Best Regards,

Alex

**Comment by jbuchhammer** [comment]
Hi Alex,
works - thanks very much!
